### ISSUE TITLE
Bug: Blank space added for one-line, no-content nodes

### ISSUE THREAD

**Issue by CasualDeveloper** [patrickvuarnoz/nova-beautify#6]
Can we disable the extension's behaviour to add blank space before the `/>` in one-line, no-content nodes?

So instead of making it look like this:
<img width="420" alt="Screenshot 2021-03-12 at 12 00 55 PM" src="https://user-images.githubusercontent.com/10153929/110890259-a41a8a80-832a-11eb-869c-876ad937f286.png">

I want the formatted result look like this:
<img width="422" alt="Screenshot 2021-03-12 at 11 59 50 AM" src="https://user-images.githubusercontent.com/10153929/110890167-759caf80-832a-11eb-9d8c-2a76db57b5da.png">

**Comment by patrickvuarnoz** [comment]
Unfortunately there is no option in js-beautify that covers that. I found an open issue on js-beautify that asks exactly for that:
https://github.com/beautify-web/js-beautify/issues/654

**Comment by CasualDeveloper** [comment]
Hi Patrick, thanks for the reply - I understand now it's a limitation of the library and not of the extension.

I have a slight question though, why do the Parameter nodes still get formatted, if I've set to exclude them in the extension settings? Wouldn't these settings cause the extension to ignore them?

<img width="1508" alt="Screenshot 2021-03-23 at 12 15 43 PM" src="https://user-images.githubusercontent.com/10153929/112422891-94f4fd00-8d6c-11eb-89e6-11296758534f.png">

**Comment by patrickvuarnoz** [comment]
Hi Kai, I think this is a bug in Nova and I somehow remember of having read that before. Nova sometimes doesn't update the settings correctly when changes have been made in textfields. 

I my tests, if you change the contents of `unformatted tags`, then switch in the extension library to another extension and then back to Beautify, then the settings have been set. This is weird but cannot be influenced by the extension. As said, it's Nova bug.

I then played around a bit to get to your desired result. It turns out that if you set `parameter` instead of `Parameter` then it actually does not reformat your `<Parameter>` tags. It seems that JS-Beautify wants the tag names in lowercase. But I cannot completely confirm that yet, I'd have to investigate the JS-Beautify code.

After your `<Parameter>` tags are already formatted like you have them in the picture you posted, they will not get reformatted to a single line when you set `unformatted tags` to `parameter`. This is because they are the considered to be left unformatted, i.e. as is.

There would be another option in JS-Beautify which specifies tags as `inline tags`. I didn't get that to work properly but it would probably be the thing you were actually looking for. I'll have a look into that sometime in the next days.

**Comment by patrickvuarnoz** [comment]
Had a look into inline tags but it didn't have the desired (or any predictable) effect. So I did not include that yet. But I added a logging of the config options so you see in the extension console which values are actually used for formatting. Also all tag names are now lowercased automatically so it does not matter anymore if you enter `<Parameter>` or `<parameter>`.

**Comment by CasualDeveloper** [comment]
Hi Patrick,

Sorry to bring this up again, but trying what you suggested did not seem to work.

This is before formatting:
<img width="500" alt="Screenshot 2021-03-26 at 10 09 39 PM" src="https://user-images.githubusercontent.com/10153929/112644574-8c8de680-8e80-11eb-8a6e-06c90712238d.png">

And this is after:
<img width="500" alt="Screenshot 2021-03-26 at 10 06 01 PM" src="https://user-images.githubusercontent.com/10153929/112644747-b6dfa400-8e80-11eb-917d-a34f83e83a81.png">


I'm using the below settings for the Extension because I want the Parameter nodes to always be formatted in new lines, but I don't want whatever is within the node, such as its attributes or the closing brace, to be formatted.
<img width="500" alt="Screenshot 2021-03-26 at 10 10 06 PM" src="https://user-images.githubusercontent.com/10153929/112644242-2739f580-8e80-11eb-9da9-d89c4c334092.png">

**Comment by patrickvuarnoz** [comment]
Hi Kai, I meant to put `bean:parameter,ins:parameter,parameter` into `unformatted tags`, not `unformatted content`. `unformatted tags` leaves those tags completely untouched while `unformatted content` just doesn't touch the contents of these tags, i.e. what's inside <parameter></parameter>.

**Comment by CasualDeveloper** [comment]
Hi Patrick, sorry to bother you again; but yes, I want the tag itself to be formatted but not what's inside.

Unfortunately, putting the tags in `unformatted tags` will cause the extension to ignore the tags if there are multiples of them in a single line (which I don't want):
<img width="500" alt="Screenshot 2021-03-31 at 10 28 33 AM" src="https://user-images.githubusercontent.com/10153929/113081926-32887a80-920c-11eb-8069-699528350ce6.png">

It also looks like tags with namespaces don't seem to work - I've tried excluding `ins:parameter` in both `unformatted tags` and `unformatted content` but they still got formatted:
<img width="500" alt="Screenshot 2021-03-31 at 10 28 56 AM" src="https://user-images.githubusercontent.com/10153929/113082069-65cb0980-920c-11eb-9032-dd962140091b.png">

**Comment by patrickvuarnoz** [comment]
Hi Kai, I can confirm your problem with the `<ins:parameter>` and multiple tags on one line. But it goes beyond my powers to offer you a solution. It's how js-beautify works. The Nova extension only passes the config into js-beautify and does not add any other magic stuff.

If you manage to find a working combination of config options with js-beautify on the command line or with the javascript version (see installation here https://github.com/beautify-web/js-beautify#installation) then let me know and I can investigate why that would not work in the Nova extension.

You might also consider using the Prettier extension by Alexander Weiss (nova://extension/?id=alexanderweiss.prettier&name=Prettier). It's the most popular extension/formatter for Nova.
