### ISSUE TITLE
Support for .Liquid files

### ISSUE THREAD

**Issue by ckizer** [patrickvuarnoz/nova-beautify#7]
Shopify .liquid files is essentially HTML that has additional bracketed tags. 
If you could allow beautify to work on .liquid files exactly as it does on HTML files that would be amazing.

Currently I have to:
1)  toggle my .liquid file to html
2) Run Beautify
3) toggle html file back to liquid format

**Comment by patrickvuarnoz** [comment]
Nova does not per se recognize the .liquid files as a separate syntax. Instead it opens them as `Plain Text`. For the Beautify extension I need to know what syntax the contents are and that information comes from Nova. 

I had a look at Liquid extension from arthr:
nova://extension/?id=me.arthr.Liquid&name=Liquid

If you have installed that extension then Nova reports the syntax as `liquid-html` which comes from arthr's extension and that syntax defines that `liquid-html` is a sub-syntax of `html`. Unfortunately Nova does not expose the parent-syntax `html` to the extension code. So I would have to hard-code a mapping of `liquid-html` (and other syntaxes) to `html`  which is not a viable solution in the long run (since obviously the identifier of a sub-syntax might change or there might be just too many to support).

I filed a feature request with Nova for them to expose the parent-syntax.

In the meantime I'd suggest to either:

- work with .html files instead of .liquid – arthr seems to do so too in the screenshot shown from his extension
- stick with .liquid files and use `Beautify > Format as HTML, XML`

**Comment by patrickvuarnoz** [comment]
Just released version 1.6 of the extension which enables formatting of liquid files. You have to activate arthr's extension first for it to work. See nova://extension/?id=me.arthr.Liquid&name=Liquid.
