### ISSUE TITLE
Unformatting

### ISSUE THREAD

**Issue by elemis** [patrickvuarnoz/nova-beautify#8]
I'm using gulp-file-include to include partials in my html files. This is how I call for partials:
```
     @@include('footer.html')
     @@include('scripts.html')
```

Beautifying removes the indentation and merges two includes in a single line like this:

`@@include('footer.html') @@include('scripts.html')`

Any chance to add exceptions for @@include so those lines stay unformatted?

**Comment by patrickvuarnoz** [comment]
Hi elemis,

if you toggle `Preserve existing line-breaks` to `ON` for HTML & XML formatting in the Beautify preferences, it will not merge the two @@includes onto one line. 

Would that already solve your problem? 

Best,
Patrick

**Comment by elemis** [comment]
Hmm that will cause other issues like not removing unwanted extra lines and spaces. Any other options?

**Comment by patrickvuarnoz** [comment]
I quickly checked if there are possibilities to ignore stuff in js-beautify. See https://github.com/beautify-web/js-beautify#directives. According to that an option is to do the following:
```
<!-- beautify ignore:start -->
@@include('footer.html')
@@include('scripts.html')
<!-- beautify ignore:end -->
```

This seems to work but you have to have those additional tags in your files. Further than that I do not see any options since the Beautify extension is only a wrapper around js-beautify.

**Comment by elemis** [comment]
Unfortunately this causes beautify ignore in output HTML as well. Wish there was another way :(
